# Usage:
#   docker-compose up --force-recreate
version: '3'

services:
  #--------------#

  jenkins_test:
     
#    build: .
#    dockerfile: Dockerfile
    image: "jamesz2011/apitestenv_jenkins_bete1"
    container_name: jenkins_test21
    tty: true
    volumes:
      - /opt/jenkins-data:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 7779:8080
      - 54200:50000
      - 233:22

    environment:

     # JDK_VERSION: "1.8.131"
    #  JAVA_HOME: "/opt/jdk${JDK_VERSION}"
   #   JRE_HOME: "${JAVA_HOME}/jre"
  #    CLASSPATH: ".:${JAVA_HOME}/lib:${JRE_HOME}/lib"
 #     PATH: "${JAVA_HOME}/bin:$PATH" 
      JAVA_OPTS: "-Djava.awt.headless=true"
      JAVA_OPTS: "-Dfile.encoding=UTF-8"

    restart: always
