# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  dockerUIi:
    image: "uifd/ui-for-docker"
    container_name: dockerUI
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 9000:9000



